l:linked_list.o main.o
	gcc  linked_list.o main.o -o l -g 
main.o:main.c
	gcc -Wall -Werror -pedantic-errors -c main.c -g 
linked_list.o:linked_list.c
	gcc -Wall -Werror -pedantic-errorors -c linked_list.c -g 
